

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 73047230569403d76aa25e149207ba24
            client-secret: nOWuLhsEVbByRFf3pvpGMlRDF8R7HFmC
            redirect-uri: http://localhost:6090/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id